/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and receive JWTs */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthLoginRequest"];
                };
            };
            responses: {
                /** @description Tokens issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthLoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get token balance */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Balance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenBalanceResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reserve tokens for a job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TokenReserveRequest"];
                };
            };
            responses: {
                /** @description Reserved or insufficient */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release reserved tokens for a job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TokenReserveRequest"];
                };
            };
            responses: {
                /** @description Released */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/deduct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deduct tokens after a job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TokenDeductRequest"];
                };
            };
            responses: {
                /** @description Deducted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new encode job
         * @description Create a job for upload ingest (returns a presigned PUT) or direct URL/S3 ingest.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JobCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobCreateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/probe-duration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Probe input duration */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Duration probed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProbeDurationResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/approve-unified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve, probe, reserve, and return estimate (does not enqueue) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ApproveUnifiedRequest"];
                };
            };
            responses: {
                /** @description Approved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApproveUnifiedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm job and enqueue (reserves if not already reserved) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ConfirmRequest"];
                };
            };
            responses: {
                /** @description Confirmed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfirmResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get status for an authenticated job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a job (created/queued) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Canceled or no-op */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API keys */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of keys */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKeyListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create an API key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApiKeyCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKeyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List webhooks
         * @description List managed webhook subscriptions for the authenticated user. Managed webhook deliveries include HMAC-SHA256 signatures.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of webhooks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a webhook
         * @description Create a managed webhook subscription. The response includes `secret` exactly once.
         *     Store it securely and use it to verify `X-Webhook-Signature`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WebhookCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test a webhook
         * @description Sends a `webhook.test` event to the configured URL using the same HMAC signature header as managed deliveries.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Test event sent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Delete a webhook */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a webhook */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WebhookUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/jobs/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk create jobs */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BulkCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BulkCreateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/bulk/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bulk status check */
        get: {
            parameters: {
                query: {
                    ids: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statuses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BulkStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/bulk/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk confirm/enqueue jobs */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BulkConfirmRequest"];
                };
            };
            responses: {
                /** @description Confirmed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            queued?: number;
                            jobs?: Record<string, never>[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/stream/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initialize streaming ingest */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StreamInitResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/stream/chunk/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload a streaming chunk */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    index: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/octet-stream": string;
                };
            };
            responses: {
                /** @description Chunk received */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/stream/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize streaming and complete upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StreamFinalizeRequest"];
                };
            };
            responses: {
                /** @description Finalized */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/stream/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abort streaming */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aborted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a public job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        codec: "h264" | "h265" | "av1";
                        /** @enum {string} */
                        resolution: "480p" | "720p";
                        fps: number;
                        /** @enum {string} */
                        container?: "mp4" | "mkv" | "mov" | "webm";
                        /**
                         * Format: uri
                         * @description Optional direct URL ingest
                         */
                        sourceUrl?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobCreateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/jobs/{id}/probe-duration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Probe duration for public job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Duration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProbeDurationResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/jobs/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm and enqueue a public job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ConfirmRequest"];
                };
            };
            responses: {
                /** @description Confirmed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/jobs/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get status for a public job (tokenized) */
        get: {
            parameters: {
                query: {
                    token: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ondemand/encode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit video for immediate on-demand encoding
         * @description Simplified API for immediate video encoding. Automatically probes, reserves tokens,
         *     and starts encoding. Premium pricing (1.5x-2x) for on-demand convenience.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OnDemandEncodeRequest"];
                };
            };
            responses: {
                /** @description Job created and queued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnDemandEncodeResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient tokens */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Deprecated Dropbox destination requested */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ondemand/ingest/folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest videos from an S3 or Google Drive folder
         * @description Crawls an S3 prefix or Google Drive folder, queues one encode job per video file,
         *     and optionally delivers outputs to CDN, S3, or Google Drive.
         *
         *     For API integrations, Google Drive can be used without dashboard OAuth by passing
         *     `accessToken` in `sourceGoogleDrive` and/or `outputGoogleDrive`.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OnDemandFolderIngestRequest"];
                };
            };
            responses: {
                /** @description Folder jobs queued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnDemandFolderIngestResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing or expired Google Drive token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No video files found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Deprecated Dropbox source or destination requested */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ondemand/status/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get on-demand job status and download URL */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnDemandStatusResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ondemand/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel on-demand encoding job */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job canceled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            released?: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthLoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthLoginResponse: {
            accessToken?: string;
            refreshToken?: string;
        };
        TokenBalanceResponse: {
            available?: number;
            reserved?: number;
            trialGrantRemaining?: number;
            /** Format: date-time */
            trialExpiresAt?: string | null;
        };
        TokenReserveRequest: {
            /** Format: uuid */
            jobId: string;
            amount: number;
        };
        TokenDeductRequest: {
            /** Format: uuid */
            jobId: string;
            amount: number;
        };
        JobCreateRequest: {
            /** @enum {string} */
            codec: "h264" | "h265" | "av1";
            /** @enum {string} */
            resolution: "480p" | "720p" | "1080p" | "1440p" | "2160p" | "4320p";
            fps: number;
            /**
             * @default mp4
             * @enum {string}
             */
            container?: "mp4" | "mkv" | "webm" | "mov";
            /**
             * @default fast
             * @enum {string}
             */
            preset?: "fast" | "standard" | "slow";
            /**
             * @default medium
             * @enum {string}
             */
            bitrateTier?: "low" | "medium" | "high";
            /**
             * @default 1
             * @enum {integer}
             */
            passes?: 1 | 2;
            /**
             * @default gpu_first
             * @enum {string}
             */
            policy?: "fastest" | "gpu_first" | "gpu_only";
            /** @enum {string} */
            quality?: "good" | "better" | "best";
            /**
             * Format: uri
             * @description Optional direct HTTP(S) ingest. When provided, upload URL is not returned.
             */
            sourceUrl?: string;
            sourceS3?: {
                bucket?: string;
                key?: string;
                endpoint?: string;
                region?: string;
                accessKeyId?: string;
                secretAccessKey?: string;
                forcePathStyle?: boolean;
            };
            /** @default false */
            confirm?: boolean;
            /** @enum {string} */
            optimize?: "none" | "vmaf";
            vmafTarget?: number;
        };
        JobCreateResponse: {
            jobId: string;
            upload: {
                url?: string;
                key?: string;
            } | null;
            output: {
                key?: string;
                publicUrl?: string;
            };
            estimate?: {
                neu?: number;
            };
        };
        ProbeDurationResponse: {
            durationSec?: number;
            durationMinutes?: number;
        };
        ApproveUnifiedRequest: {
            /** @enum {string} */
            codec?: "h264" | "h265" | "av1";
            resolution?: string;
            fps?: number;
            /** @enum {string} */
            preset?: "fast" | "standard" | "slow";
            /** @enum {string} */
            bitrateTier?: "low" | "medium" | "high";
            /** @enum {integer} */
            passes?: 1 | 2;
            /** @enum {string} */
            policy?: "gpu_only" | "gpu_first" | "fastest";
            /** @enum {string} */
            container?: "mp4" | "mkv" | "webm" | "mov";
            /** @enum {string} */
            quality?: "good" | "better" | "best";
            /** @enum {string} */
            optimize?: "none" | "vmaf";
            vmafTarget?: number;
        };
        ApproveUnifiedResponse: {
            ok?: boolean;
            estimate?: {
                perMinuteNeu?: number;
                durationSec?: number;
                totalNeu?: number;
                reserved?: number;
            };
        };
        ConfirmRequest: {
            /** @enum {string} */
            container?: "mp4" | "mkv" | "webm" | "mov";
            /** @enum {string} */
            quality?: "good" | "better" | "best";
            /** @enum {string} */
            optimize?: "none" | "vmaf";
            vmafTarget?: number;
        };
        ConfirmResponse: {
            ok?: boolean;
        };
        StatusResponse: {
            id?: string;
            status?: string;
            downloadUrl?: string | null;
            encoder?: string | null;
            pct?: number | null;
        };
        ErrorResponse: {
            message?: string;
        };
        BulkCreateRequest: {
            jobs: components["schemas"]["JobCreateRequest"][];
            settings?: {
                /** @default false */
                failFast?: boolean;
                /** @default false */
                dryRun?: boolean;
                /** @default false */
                confirm?: boolean;
                /** @enum {string} */
                container?: "mp4" | "mkv" | "webm" | "mov";
                /** @enum {string} */
                quality?: "good" | "better" | "best";
                /** @enum {string} */
                optimize?: "none" | "vmaf";
                vmafTarget?: number;
            };
        };
        BulkCreateResponse: {
            totalJobs?: number;
            totalEstimatedNeu?: number;
            jobs?: {
                index?: number;
                /** Format: uuid */
                jobId?: string;
                status?: string;
                error?: string;
            }[];
        };
        BulkStatusResponse: {
            jobs?: components["schemas"]["StatusResponse"][];
            missing?: string[];
        };
        BulkConfirmRequest: {
            jobIds: string[];
            settings?: {
                /** @enum {string} */
                container?: "mp4" | "mkv" | "webm" | "mov";
                /** @enum {string} */
                quality?: "good" | "better" | "best";
            };
        };
        ApiKeyCreateRequest: {
            name: string;
            scopes?: string[];
            expiresInDays?: number;
        };
        ApiKeyResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @description Raw key, only returned on creation */
            key?: string;
            prefix?: string;
            scopes?: string[];
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiKeyListResponse: {
            keys?: components["schemas"]["ApiKeyResponse"][];
        };
        WebhookCreateRequest: {
            /** Format: uri */
            url: string;
            events: ("job.created" | "job.queued" | "job.running" | "job.completed" | "job.failed" | "job.canceled")[];
        };
        WebhookUpdateRequest: {
            /** Format: uri */
            url?: string;
            events?: ("job.created" | "job.queued" | "job.running" | "job.completed" | "job.failed" | "job.canceled")[];
            isActive?: boolean;
        };
        WebhookResponse: {
            /** Format: uuid */
            id?: string;
            url?: string;
            events?: string[];
            /** @description HMAC secret, only returned on creation */
            secret?: string;
            isActive?: boolean;
            failureCount?: number;
            /** Format: date-time */
            lastTriggeredAt?: string | null;
            /** Format: date-time */
            lastFailedAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        WebhookListResponse: {
            webhooks?: components["schemas"]["WebhookResponse"][];
        };
        S3Output: {
            bucket: string;
            key: string;
            /** Format: uri */
            endpoint?: string;
            region?: string;
            accessKeyId?: string;
            /** Format: password */
            secretAccessKey?: string;
            forcePathStyle?: boolean;
        };
        S3FolderSource: {
            bucket: string;
            /** @default  */
            prefix?: string;
            /** Format: uri */
            endpoint?: string;
            region?: string;
            accessKeyId?: string;
            /** Format: password */
            secretAccessKey?: string;
            /** @default true */
            forcePathStyle?: boolean;
        };
        S3FolderOutput: {
            bucket: string;
            /** @default outputs/ */
            prefix?: string;
            /** Format: uri */
            endpoint?: string;
            region?: string;
            accessKeyId?: string;
            /** Format: password */
            secretAccessKey?: string;
            /** @default true */
            forcePathStyle?: boolean;
        };
        GoogleDriveFolderSource: {
            folderId: string;
            /** @description Short-lived Google OAuth access token supplied by the API caller. */
            accessToken?: string;
            /** @description Optional Google refresh token supplied by the API caller for long-running jobs. */
            refreshToken?: string;
        };
        GoogleDriveOutput: {
            folderId: string;
            fileName?: string;
            /** @description Short-lived Google OAuth access token supplied by the API caller. */
            accessToken?: string;
            /** @description Optional Google refresh token supplied by the API caller for long-running jobs. */
            refreshToken?: string;
        };
        OnDemandEncodeRequest: {
            /** Format: uri */
            sourceUrl: string;
            /**
             * @default h264
             * @enum {string}
             */
            codec?: "h264" | "h265" | "av1";
            /**
             * @default 1080p
             * @enum {string}
             */
            resolution?: "480p" | "720p" | "1080p" | "1440p" | "2160p";
            /** @default 30 */
            fps?: number;
            /**
             * @default fast
             * @enum {string}
             */
            preset?: "fast" | "standard" | "slow";
            /**
             * @default medium
             * @enum {string}
             */
            bitrateTier?: "low" | "medium" | "high";
            /**
             * @default mp4
             * @enum {string}
             */
            container?: "mp4" | "mkv" | "webm" | "mov";
            /**
             * @default better
             * @enum {string}
             */
            quality?: "good" | "better" | "best";
            /**
             * @default normal
             * @enum {string}
             */
            priority?: "normal" | "high";
            /** @default 86400 */
            outputExpiry?: number;
            /**
             * Format: uri
             * @description Optional one-off terminal callback URL for this job. Best-effort and unsigned. Use managed webhooks for signed HMAC delivery.
             */
            webhook?: string;
            outputS3?: components["schemas"]["S3Output"];
            outputGoogleDrive?: components["schemas"]["GoogleDriveOutput"];
            /**
             * @deprecated
             * @description Deprecated. Requests using Dropbox output return 410 Gone.
             */
            outputDropbox?: {
                path?: string;
                accessToken?: string;
            };
        };
        OnDemandEncodeResponse: {
            /** Format: uuid */
            jobId: string;
            status: string;
            estimatedDuration?: number;
            pricing?: {
                basePerMinute?: number;
                onDemandPerMinute?: number;
                multiplier?: number;
                totalNeu?: number;
                reserved?: number;
            };
            statusUrl: string;
            webhook?: string | null;
        };
        OnDemandStatusResponse: {
            /** Format: uuid */
            jobId?: string;
            status?: string;
            progress?: number | null;
            encoder?: string | null;
            downloadUrl?: string | null;
            expiresIn?: number | null;
            destination?: ({
                /** @enum {string} */
                type?: "cdn";
            } | {
                /** @enum {string} */
                type?: "s3";
                bucket?: string;
                key?: string;
            } | {
                /** @enum {string} */
                type?: "google-drive";
                folderId?: string;
                fileName?: string | null;
            }) | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
            failureMessage?: string | null;
        };
        OnDemandFolderIngestRequest: {
            /**
             * @default h264
             * @enum {string}
             */
            codec?: "h264" | "h265" | "av1";
            /**
             * @default 1080p
             * @enum {string}
             */
            resolution?: "480p" | "720p" | "1080p" | "1440p" | "2160p" | "4320p";
            /** @default 30 */
            fps?: number;
            /**
             * @default fast
             * @enum {string}
             */
            preset?: "fast" | "standard" | "slow";
            /**
             * @default medium
             * @enum {string}
             */
            bitrateTier?: "low" | "medium" | "high";
            /** @default 1 */
            passes?: number;
            /**
             * @default none
             * @enum {string}
             */
            optimize?: "none" | "vmaf";
            vmafTarget?: number;
            /**
             * @default mp4
             * @enum {string}
             */
            container?: "mp4" | "mkv" | "webm" | "mov";
            /**
             * @default better
             * @enum {string}
             */
            quality?: "good" | "better" | "best";
            /**
             * @default normal
             * @enum {string}
             */
            priority?: "normal" | "high";
            sourceS3?: components["schemas"]["S3FolderSource"];
            sourceGoogleDrive?: components["schemas"]["GoogleDriveFolderSource"];
            /**
             * @deprecated
             * @description Deprecated. Requests using Dropbox ingest return 410 Gone.
             */
            sourceDropbox?: {
                path?: string;
                accessToken?: string;
            };
            /**
             * @default cdn
             * @enum {string}
             */
            outputDestination?: "cdn" | "s3" | "google-drive";
            outputS3?: components["schemas"]["S3FolderOutput"];
            outputGoogleDrive?: components["schemas"]["GoogleDriveOutput"];
            /**
             * @deprecated
             * @description Deprecated. Requests using Dropbox output return 410 Gone.
             */
            outputDropbox?: {
                path?: string;
            };
        };
        OnDemandFolderIngestResponse: {
            message?: string;
            jobs?: {
                /** Format: uuid */
                jobId?: string;
                fileName?: string;
            }[];
        };
        StreamInitResponse: {
            ok?: boolean;
            uploadId?: string;
            inputKey?: string;
        };
        StreamFinalizeRequest: {
            parts?: {
                PartNumber?: number;
                ETag?: string;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
