/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login and receive JWTs */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AuthLoginRequest"];
                };
            };
            responses: {
                /** @description Tokens issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthLoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get token balance */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Balance */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenBalanceResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reserve tokens for a job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TokenReserveRequest"];
                };
            };
            responses: {
                /** @description Reserved or insufficient */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release reserved tokens for a job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TokenReserveRequest"];
                };
            };
            responses: {
                /** @description Released */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/deduct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deduct tokens after a job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TokenDeductRequest"];
                };
            };
            responses: {
                /** @description Deducted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new encode job
         * @description Create a job for upload ingest (returns a presigned PUT) or direct URL/S3 ingest. Send `Idempotency-Key` when retrying from your backend to avoid duplicate jobs.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional key for safely retrying job creation requests. Reusing the same key with the same request body replays the original response; reusing it with a different body returns 409. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JobCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobCreateResponse"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/probe-duration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Probe input duration */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Duration probed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProbeDurationResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/approve-unified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve, probe, reserve, and return estimate (does not enqueue) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ApproveUnifiedRequest"];
                };
            };
            responses: {
                /** @description Approved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApproveUnifiedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm job and enqueue (reserves if not already reserved) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ConfirmRequest"];
                };
            };
            responses: {
                /** @description Confirmed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConfirmResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get status for an authenticated job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a job (created/queued) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Canceled or no-op */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API keys */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of keys */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKeyListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create an API key */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ApiKeyCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiKeyResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List webhooks
         * @description List managed webhook subscriptions for the authenticated user. API keys need the `webhooks:manage` scope. Managed webhook deliveries include HMAC-SHA256 signatures.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of webhooks */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a webhook
         * @description Create a managed webhook subscription. The response includes `secret` exactly once.
         *     Store it securely and use it to verify `X-Webhook-Signature`.
         *     API keys need the `webhooks:manage` scope.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WebhookCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test a webhook
         * @description Sends a `webhook.test` event to the configured URL using the same HMAC signature header as managed deliveries. API keys need the `webhooks:manage` scope.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Test event sent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Delete a webhook
         * @description API keys need the `webhooks:manage` scope.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a webhook
         * @description API keys need the `webhooks:manage` scope.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WebhookUpdateRequest"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/webhooks/{id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List webhook delivery attempts
         * @description Returns the 50 most recent managed or test delivery attempts for this webhook. API keys need the `webhooks:manage` scope.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recent delivery attempts */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookDeliveryListResponse"];
                    };
                };
                /** @description Webhook not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk create jobs
         * @description Send `Idempotency-Key` when retrying from your backend to avoid duplicate bulk batches, duplicate token reservations, or duplicate queue entries.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional key for safely retrying job creation requests. Reusing the same key with the same request body replays the original response; reusing it with a different body returns 409. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BulkCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BulkCreateResponse"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/bulk/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bulk status check */
        get: {
            parameters: {
                query: {
                    ids: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statuses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BulkStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/bulk/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk confirm/enqueue jobs */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BulkConfirmRequest"];
                };
            };
            responses: {
                /** @description Confirmed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            queued?: number;
                            jobs?: Record<string, never>[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/stream/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initialize streaming ingest */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StreamInitResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/stream/chunk/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload a streaming chunk */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    index: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/octet-stream": string;
                };
            };
            responses: {
                /** @description Chunk received */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/stream/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize streaming and complete upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["StreamFinalizeRequest"];
                };
            };
            responses: {
                /** @description Finalized */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/stream/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abort streaming */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aborted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a public job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        codec: "h264" | "h265" | "av1";
                        /** @enum {string} */
                        resolution: "480p" | "720p";
                        fps: number;
                        /** @enum {string} */
                        container?: "mp4" | "mkv" | "mov" | "webm";
                        /**
                         * Format: uri
                         * @description Optional direct URL ingest
                         */
                        sourceUrl?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobCreateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/jobs/{id}/probe-duration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Probe duration for public job */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Duration */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProbeDurationResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/jobs/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm and enqueue a public job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ConfirmRequest"];
                };
            };
            responses: {
                /** @description Confirmed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/jobs/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get status for a public job (tokenized) */
        get: {
            parameters: {
                query: {
                    token: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ondemand/credentials/google-drive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved Google Drive service-account credentials */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Credential metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            credentials?: components["schemas"]["GoogleDriveCredential"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Save an encrypted Google Drive service-account credential */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GoogleDriveCredentialCreate"];
                };
            };
            responses: {
                /** @description Credential saved */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GoogleDriveCredential"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ondemand/credentials/google-drive/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a Google Drive service-account credential */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Credential deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ondemand/encode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit video for immediate on-demand encoding
         * @description Simplified API for immediate video encoding. Automatically probes, reserves tokens,
         *     and starts encoding. Premium pricing (1.5x-2x) for on-demand convenience.
         *     Send `Idempotency-Key` when retrying from your backend to avoid duplicate jobs.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional key for safely retrying job creation requests. Reusing the same key with the same request body replays the original response; reusing it with a different body returns 409. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OnDemandEncodeRequest"];
                };
            };
            responses: {
                /** @description Job created and queued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnDemandEncodeResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Insufficient tokens */
                402: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Deprecated Dropbox destination requested */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ondemand/ingest/folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest videos from an S3 or Google Drive folder
         * @description Crawls an S3 prefix or Google Drive folder, queues one encode job per video file,
         *     and optionally delivers outputs to CDN, S3, or Google Drive.
         *
         *     For API integrations, use bring-your-own credentials:
         *     - S3-compatible storage: pass `sourceS3` and/or `outputS3` credentials from your backend.
         *     - Google Drive: save a customer-owned service account, share the folders with its client email,
         *       and pass its `credentialId` in `sourceGoogleDrive` and/or `outputGoogleDrive`.
         *     Send `Idempotency-Key` when retrying from your backend to avoid duplicate folder batches.
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @description Optional key for safely retrying job creation requests. Reusing the same key with the same request body replays the original response; reusing it with a different body returns 409. */
                    "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OnDemandFolderIngestRequest"];
                };
            };
            responses: {
                /** @description Folder jobs queued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnDemandFolderIngestResponse"];
                    };
                };
                /** @description Invalid request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Missing dashboard Google Drive connection */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description No video files found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Deprecated Dropbox source or destination requested */
                410: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ondemand/status/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get on-demand job status and download URL */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OnDemandStatusResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Rate limit exceeded */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ondemand/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel on-demand encoding job */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Job canceled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            released?: number;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthLoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthLoginResponse: {
            accessToken?: string;
            refreshToken?: string;
        };
        TokenBalanceResponse: {
            available?: number;
            reserved?: number;
            trialGrantRemaining?: number;
            /** Format: date-time */
            trialExpiresAt?: string | null;
        };
        TokenReserveRequest: {
            /** Format: uuid */
            jobId: string;
            amount: number;
        };
        TokenDeductRequest: {
            /** Format: uuid */
            jobId: string;
            amount: number;
        };
        JobCreateRequest: {
            /** @description Your stable job identifier for reconciliation in status responses and webhooks. */
            externalId?: string;
            /** @description Integration-owned JSON object returned in status responses and webhooks. */
            metadata?: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            codec: "h264" | "h265" | "av1";
            /** @enum {string} */
            resolution: "480p" | "720p" | "1080p" | "1440p" | "2160p" | "4320p";
            fps: number;
            /**
             * @default mp4
             * @enum {string}
             */
            container?: "mp4" | "mkv" | "webm" | "mov";
            /**
             * @default fast
             * @enum {string}
             */
            preset?: "fast" | "standard" | "slow";
            /**
             * @default medium
             * @enum {string}
             */
            bitrateTier?: "low" | "medium" | "high";
            /**
             * @description Requested encoding passes. When optimize is vmaf, the API uses and bills one effective final pass.
             * @default 1
             * @enum {integer}
             */
            passes?: 1 | 2;
            /**
             * @default gpu_first
             * @enum {string}
             */
            policy?: "fastest" | "gpu_first" | "gpu_only";
            /** @enum {string} */
            quality?: "good" | "better" | "best";
            /**
             * Format: uri
             * @description Optional direct HTTP(S) ingest. When provided, upload URL is not returned.
             */
            sourceUrl?: string;
            /** @description Optional source filename used to generate human-readable output download names. */
            originalFilename?: string;
            sourceS3?: {
                bucket?: string;
                key?: string;
                endpoint?: string;
                region?: string;
                accessKeyId?: string;
                secretAccessKey?: string;
                forcePathStyle?: boolean;
            };
            /** @default false */
            confirm?: boolean;
            /** @enum {string} */
            optimize?: "none" | "vmaf";
            vmafTarget?: number;
        };
        JobCreateResponse: {
            jobId: string;
            externalId?: string | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
            sourceFilename?: string | null;
            outputFilename?: string | null;
            /** @description Present when the job is auto-confirmed and queued. */
            status?: string;
            upload: {
                url?: string;
                key?: string;
            } | null;
            output: {
                key?: string;
                publicUrl?: string;
            };
            estimate?: {
                neu?: number;
                totalNeu?: number;
                reserved?: number;
                /** @enum {integer} */
                requestedPasses?: 1 | 2;
                /**
                 * @description Pass count actually used for pricing and encoding. VMAF requests use 1.
                 * @enum {integer}
                 */
                effectivePasses?: 1 | 2;
            };
        };
        ProbeDurationResponse: {
            durationSec?: number;
            durationMinutes?: number;
        };
        ApproveUnifiedRequest: {
            /** @enum {string} */
            codec?: "h264" | "h265" | "av1";
            resolution?: string;
            fps?: number;
            /** @enum {string} */
            preset?: "fast" | "standard" | "slow";
            /** @enum {string} */
            bitrateTier?: "low" | "medium" | "high";
            /**
             * @description Requested passes. Ignored for execution and billing when optimize is vmaf.
             * @enum {integer}
             */
            passes?: 1 | 2;
            /** @enum {string} */
            policy?: "gpu_only" | "gpu_first" | "fastest";
            /** @enum {string} */
            container?: "mp4" | "mkv" | "webm" | "mov";
            /** @enum {string} */
            quality?: "good" | "better" | "best";
            /** @enum {string} */
            optimize?: "none" | "vmaf";
            vmafTarget?: number;
        };
        ApproveUnifiedResponse: {
            ok?: boolean;
            estimate?: {
                perMinuteNeu?: number;
                durationSec?: number;
                totalNeu?: number;
                reserved?: number;
                /** @enum {integer} */
                requestedPasses?: 1 | 2;
                /**
                 * @description Pass count used for pricing and execution.
                 * @enum {integer}
                 */
                effectivePasses?: 1 | 2;
            };
        };
        ConfirmRequest: {
            /** @enum {string} */
            container?: "mp4" | "mkv" | "webm" | "mov";
            /** @enum {string} */
            quality?: "good" | "better" | "best";
            /** @enum {string} */
            optimize?: "none" | "vmaf";
            vmafTarget?: number;
        };
        ConfirmResponse: {
            ok?: boolean;
        };
        StatusResponse: {
            id?: string;
            externalId?: string | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
            sourceFilename?: string | null;
            outputFilename?: string | null;
            status?: string;
            ingest?: string | null;
            output?: {
                key?: string;
                publicUrl?: string;
            } | null;
            downloadUrl?: string | null;
            encoder?: string | null;
            pct?: number | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
            failureMessage?: string | null;
        };
        ErrorResponse: {
            /**
             * @description Stable machine-readable error code. Branch on this instead of parsing `message`.
             * @enum {string}
             */
            code: "invalid_api_key" | "api_key_expired" | "user_not_found" | "account_banned" | "missing_required_scope" | "invalid_request" | "invalid_body" | "invalid_url" | "url_ingest_disabled" | "url_host_blocked" | "signed_url_required" | "host_not_resolvable" | "private_ip_blocked" | "missing_content_length" | "file_too_large" | "unsupported_content_type" | "probe_failed" | "insufficient_tokens" | "idempotency_conflict" | "idempotency_in_progress" | "rate_limit_exceeded" | "not_found" | "forbidden" | "deprecated_dropbox" | "google_drive_not_connected" | "dropbox_not_connected" | "no_video_files_found" | "webhook_limit_exceeded" | "webhook_not_found" | "no_updates_provided" | "output_not_available";
            message: string;
            /** @description Validation details for `invalid_body`. */
            issues?: unknown;
            requiredScope?: string;
            required?: number;
            available?: number;
        };
        BulkCreateRequest: {
            jobs: components["schemas"]["JobCreateRequest"][];
            settings?: {
                /** @default false */
                failFast?: boolean;
                /** @default false */
                dryRun?: boolean;
                /** @default false */
                confirm?: boolean;
                /** @enum {string} */
                container?: "mp4" | "mkv" | "webm" | "mov";
                /** @enum {string} */
                quality?: "good" | "better" | "best";
                /** @enum {string} */
                optimize?: "none" | "vmaf";
                vmafTarget?: number;
            };
        };
        BulkCreateResponse: {
            totalJobs?: number;
            totalEstimatedNeu?: number;
            reserved?: number;
            jobs?: {
                index?: number;
                /** Format: uuid */
                jobId?: string;
                externalId?: string | null;
                metadata?: {
                    [key: string]: unknown;
                } | null;
                status?: string;
                error?: string;
                estimate?: {
                    neu?: number;
                };
            }[];
        };
        BulkStatusResponse: {
            jobs?: components["schemas"]["StatusResponse"][];
            missing?: string[];
        };
        BulkConfirmRequest: {
            jobIds: string[];
            settings?: {
                /** @enum {string} */
                container?: "mp4" | "mkv" | "webm" | "mov";
                /** @enum {string} */
                quality?: "good" | "better" | "best";
            };
        };
        ApiKeyCreateRequest: {
            name: string;
            /**
             * @description Requested API key scopes. Use the minimum scopes needed:
             *     `jobs:create`, `jobs:read`, `jobs:cancel`, `tokens:read`,
             *     `webhooks:manage`, and `credentials:manage` for saved storage credential management.
             */
            scopes?: ("jobs:create" | "jobs:read" | "jobs:cancel" | "tokens:read" | "tokens:write" | "webhooks:manage" | "credentials:manage")[];
            expiresInDays?: number;
        };
        ApiKeyResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** @description Raw key, only returned on creation */
            key?: string;
            prefix?: string;
            scopes?: ("jobs:create" | "jobs:read" | "jobs:cancel" | "tokens:read" | "tokens:write" | "webhooks:manage" | "credentials:manage")[];
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        ApiKeyListResponse: {
            keys?: components["schemas"]["ApiKeyResponse"][];
        };
        WebhookCreateRequest: {
            /** Format: uri */
            url: string;
            events: ("job.created" | "job.queued" | "job.running" | "job.completed" | "job.failed" | "job.canceled")[];
        };
        WebhookUpdateRequest: {
            /** Format: uri */
            url?: string;
            events?: ("job.created" | "job.queued" | "job.running" | "job.completed" | "job.failed" | "job.canceled")[];
            isActive?: boolean;
        };
        WebhookResponse: {
            /** Format: uuid */
            id?: string;
            url?: string;
            events?: string[];
            /** @description HMAC secret, only returned on creation */
            secret?: string;
            isActive?: boolean;
            failureCount?: number;
            /** Format: date-time */
            lastTriggeredAt?: string | null;
            /** Format: date-time */
            lastFailedAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        WebhookListResponse: {
            webhooks?: components["schemas"]["WebhookResponse"][];
        };
        WebhookDeliveryResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            webhookId?: string;
            event?: string;
            /** Format: uuid */
            jobId?: string | null;
            /** @enum {string} */
            status?: "success" | "failed";
            statusCode?: number | null;
            durationMs?: number | null;
            /** @description Response body captured from the receiver, truncated to 2048 characters. */
            responseBody?: string | null;
            /** @description Network, timeout, or delivery error, truncated to 2048 characters. */
            error?: string | null;
            attempt?: number;
            /** Format: date-time */
            nextRetryAt?: string | null;
            /** Format: date-time */
            retriedAt?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        WebhookDeliveryListResponse: {
            deliveries?: components["schemas"]["WebhookDeliveryResponse"][];
        };
        S3Output: {
            bucket: string;
            key: string;
            /** Format: uri */
            endpoint?: string;
            region?: string;
            accessKeyId?: string;
            /** Format: password */
            secretAccessKey?: string;
            forcePathStyle?: boolean;
        };
        /** @description Customer-owned S3-compatible folder source. Credentials should allow listing the prefix and reading objects. */
        S3FolderSource: {
            bucket: string;
            /**
             * @description Prefix to crawl. Only files with video extensions are queued.
             * @default
             */
            prefix?: string;
            /**
             * Format: uri
             * @description Optional S3-compatible endpoint, for example Cloudflare R2, MinIO, or object storage providers.
             */
            endpoint?: string;
            region?: string;
            /** @description Optional source access key. Omit only when your backend/runtime provides credentials another way. */
            accessKeyId?: string;
            /** Format: password */
            secretAccessKey?: string;
            /** @default true */
            forcePathStyle?: boolean;
        };
        /** @description Customer-owned S3-compatible output destination. Credentials should allow writing encoded objects. */
        S3FolderOutput: {
            bucket: string;
            /**
             * @description Output key prefix. The source file name is appended to this prefix.
             * @default outputs/
             */
            prefix?: string;
            /**
             * Format: uri
             * @description Optional S3-compatible endpoint, for example Cloudflare R2, MinIO, or object storage providers.
             */
            endpoint?: string;
            region?: string;
            /** @description Optional output access key. Omit only when your backend/runtime provides credentials another way. */
            accessKeyId?: string;
            /** Format: password */
            secretAccessKey?: string;
            /** @default true */
            forcePathStyle?: boolean;
        };
        /** @description Google Drive folder source for headless API integrations. The saved service account must have Reader access to the folder. */
        GoogleDriveFolderSource: {
            folderId: string;
            /** Format: uuid */
            credentialId: string;
        };
        GoogleDriveSelectedFile: {
            fileId: string;
            fileName: string;
            mimeType?: string;
        };
        /** @description Google Drive output destination. SDK callers provide a saved service-account credential ID; dashboard callers use their connected drive.file grant. */
        GoogleDriveOutput: {
            folderId: string;
            fileName?: string;
            /** Format: uuid */
            credentialId?: string;
        };
        GoogleDriveCredentialCreate: {
            name: string;
            serviceAccount: string | {
                [key: string]: unknown;
            };
        };
        GoogleDriveCredential: {
            /** Format: uuid */
            id?: string;
            name?: string;
            clientEmail?: string;
            projectId?: string | null;
            /** Format: date-time */
            createdAt?: string;
        };
        OnDemandEncodeRequest: {
            /** Format: uri */
            sourceUrl: string;
            /** @description Your stable job identifier for reconciliation in status responses and webhooks. */
            externalId?: string;
            /** @description Integration-owned JSON object returned in status responses and webhooks. */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * @default h264
             * @enum {string}
             */
            codec?: "h264" | "h265" | "av1";
            /**
             * @default 1080p
             * @enum {string}
             */
            resolution?: "480p" | "720p" | "1080p" | "1440p" | "2160p";
            /** @default 30 */
            fps?: number;
            /**
             * @default fast
             * @enum {string}
             */
            preset?: "fast" | "standard" | "slow";
            /**
             * @default medium
             * @enum {string}
             */
            bitrateTier?: "low" | "medium" | "high";
            /**
             * @default mp4
             * @enum {string}
             */
            container?: "mp4" | "mkv" | "webm" | "mov";
            /**
             * @default better
             * @enum {string}
             */
            quality?: "good" | "better" | "best";
            /**
             * @default normal
             * @enum {string}
             */
            priority?: "normal" | "high";
            /** @default 86400 */
            outputExpiry?: number;
            /**
             * Format: uri
             * @description Optional one-off terminal callback URL for this job. Best-effort and unsigned. Use managed webhooks for signed HMAC delivery.
             */
            webhook?: string;
            outputS3?: components["schemas"]["S3Output"];
            outputGoogleDrive?: components["schemas"]["GoogleDriveOutput"];
            /**
             * @deprecated
             * @description Deprecated. Requests using Dropbox output return 410 Gone.
             */
            outputDropbox?: {
                path?: string;
                accessToken?: string;
            };
        };
        OnDemandEncodeResponse: {
            /** Format: uuid */
            jobId: string;
            externalId?: string | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
            sourceFilename?: string | null;
            outputFilename?: string | null;
            status: string;
            estimatedDuration?: number;
            pricing?: {
                basePerMinute?: number;
                onDemandPerMinute?: number;
                multiplier?: number;
                totalNeu?: number;
                reserved?: number;
                /** @enum {integer} */
                requestedPasses?: 1 | 2;
                /**
                 * @description Pass count used for pricing and execution. VMAF requests use 1.
                 * @enum {integer}
                 */
                effectivePasses?: 1 | 2;
            };
            statusUrl: string;
            webhook?: string | null;
        };
        OnDemandStatusResponse: {
            /** Format: uuid */
            jobId?: string;
            externalId?: string | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
            sourceFilename?: string | null;
            outputFilename?: string | null;
            status?: string;
            progress?: number | null;
            encoder?: string | null;
            downloadUrl?: string | null;
            expiresIn?: number | null;
            destination?: ({
                /** @enum {string} */
                type?: "cdn";
            } | {
                /** @enum {string} */
                type?: "s3";
                bucket?: string;
                key?: string;
            } | {
                /** @enum {string} */
                type?: "google-drive";
                folderId?: string;
                fileName?: string | null;
            }) | null;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            startedAt?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
            failureMessage?: string | null;
        };
        OnDemandFolderIngestRequest: {
            /** @description Optional prefix used to generate one externalId per queued file as `${externalIdPrefix}:${fileName}`. */
            externalIdPrefix?: string;
            /** @description Integration-owned JSON object attached to every queued job and returned in webhooks/status responses. */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * @default h264
             * @enum {string}
             */
            codec?: "h264" | "h265" | "av1";
            /**
             * @default 1080p
             * @enum {string}
             */
            resolution?: "480p" | "720p" | "1080p" | "1440p" | "2160p" | "4320p";
            /** @default 30 */
            fps?: number;
            /**
             * @default fast
             * @enum {string}
             */
            preset?: "fast" | "standard" | "slow";
            /**
             * @default medium
             * @enum {string}
             */
            bitrateTier?: "low" | "medium" | "high";
            /**
             * @description Requested passes. VMAF optimization always uses and bills one effective final pass.
             * @default 1
             */
            passes?: number;
            /**
             * @default none
             * @enum {string}
             */
            optimize?: "none" | "vmaf";
            vmafTarget?: number;
            /**
             * @default mp4
             * @enum {string}
             */
            container?: "mp4" | "mkv" | "webm" | "mov";
            /**
             * @default better
             * @enum {string}
             */
            quality?: "good" | "better" | "best";
            /**
             * @default normal
             * @enum {string}
             */
            priority?: "normal" | "high";
            /** @description Optional cap on the number of discovered video files to queue from the folder. */
            maxFiles?: number;
            sourceS3?: components["schemas"]["S3FolderSource"];
            sourceGoogleDrive?: components["schemas"]["GoogleDriveFolderSource"];
            sourceGoogleDriveFiles?: components["schemas"]["GoogleDriveSelectedFile"][];
            /**
             * @deprecated
             * @description Deprecated. Requests using Dropbox ingest return 410 Gone.
             */
            sourceDropbox?: {
                path?: string;
                accessToken?: string;
            };
            /**
             * @default cdn
             * @enum {string}
             */
            outputDestination?: "cdn" | "s3" | "google-drive";
            outputS3?: components["schemas"]["S3FolderOutput"];
            outputGoogleDrive?: components["schemas"]["GoogleDriveOutput"];
            /**
             * @deprecated
             * @description Deprecated. Requests using Dropbox output return 410 Gone.
             */
            outputDropbox?: {
                path?: string;
            };
        };
        OnDemandFolderIngestResponse: {
            message?: string;
            jobs?: {
                /** Format: uuid */
                jobId?: string;
                externalId?: string | null;
                fileName?: string;
            }[];
        };
        StreamInitResponse: {
            ok?: boolean;
            uploadId?: string;
            inputKey?: string;
        };
        StreamFinalizeRequest: {
            parts?: {
                PartNumber?: number;
                ETag?: string;
            }[];
        };
    };
    responses: never;
    parameters: {
        /** @description Optional key for safely retrying job creation requests. Reusing the same key with the same request body replays the original response; reusing it with a different body returns 409. */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
